src/DIPS.Xamarin.UI.sln, src/DIPS.Xamarin.UI/Extensions/PropertyChangedExtensions.cs, src/Samples/DIPS.Xamarin.UI.Samples/Extensions/PropertyChangedViewModel.cs, src/Tests/DIPS.Xamarin.UI.Tests/DIPS.Xamarin.UI.Tests.csproj, src/Tests/DIPS.Xamarin.UI.Tests/Extensions/PropertyChangedExtensionsTests.cs
=> Added Notify property changed extensions

src/DIPS.Xamarin.UI/AssemblyInfo.cs, src/DIPS.Xamarin.UI/Library.cs, src/Samples/DIPS.Xamarin.UI.Samples/App.xaml, src/Samples/DIPS.Xamarin.UI.Samples/App.xaml.cs
- Todo: Add this to the Wiki -> Getting Started
=> Added the option to use Custom Namespace, Fixes #1

README.md
- Fixed a bug
- [N/A ] I have tested on an Android device.
- [N/A ] I have tested on an iOS device.
- [N/A ] I have added unit tests
=> Added space before last badge

src/DIPS.Xamarin.UI/AssemblyInfo.cs, src/DIPS.Xamarin.UI/Controls/TrendGraph/TrendGraph.xaml, src/DIPS.Xamarin.UI/Controls/TrendGraph/TrendGraph.xaml.cs, src/DIPS.Xamarin.UI/DIPS.Xamarin.UI.csproj, src/DIPS.Xamarin.UI/Extensions/ObjectExtensions.cs, src/DIPS.Xamarin.UI/Extensions/PositionExtensions.cs, src/Samples/DIPS.Xamarin.UI.Samples/Controls/ControlsPage.xaml, src/Samples/DIPS.Xamarin.UI.Samples/Controls/ControlsViewModel.cs, src/Samples/DIPS.Xamarin.UI.Samples/Controls/Popup/PopupPage.xaml, src/Samples/DIPS.Xamarin.UI.Samples/Controls/RadioButtonGroup/RadioButtonGroupPage.xaml, src/Samples/DIPS.Xamarin.UI.Samples/Controls/TrendGraph/TrendGraphPage.xaml, src/Samples/DIPS.Xamarin.UI.Samples/Controls/TrendGraph/TrendGraphPage.xaml.cs, src/Samples/DIPS.Xamarin.UI.Samples/DIPS.Xamarin.UI.Samples.csproj, src/Tests/DIPS.Xamarin.UI.Tests/Extensions/ObjectExtensionsTests.cs, src/Tests/DIPS.Xamarin.UI.Tests/Extensions/PositionsExtensionsTests.cs
=> Trend bar chart

src/DIPS.Xamarin.UI/Controls/RadioButtonGroup/RadioButtonGroup.xaml, src/DIPS.Xamarin.UI/Controls/RadioButtonGroup/RadioButtonGroup.xaml.cs, src/IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro.Android/DIPS.Xamarin.Forms.IssuesRepro.Android.csproj, src/IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro.iOS/DIPS.Xamarin.Forms.IssuesRepro.iOS.csproj, src/Samples/DIPS.Xamarin.UI.Samples/Controls/RadioButtonGroup/RadioButtonGroupPage.xaml
- Changed layout of radioButtonGroup
- This PR is for discussion. Will test properly if we decide to continue this path. (though it should work)
=> Changed layout of radioButtonGroup

src/DIPS.Xamarin.UI/Controls/RadioButtonGroup/RadioButtonGroup.xaml, src/DIPS.Xamarin.UI/Controls/RadioButtonGroup/RadioButtonGroup.xaml.cs
- Fixed the main layout of RadioButton group.
=> Used ContentView as the main layout for Radiobutton

src/DIPS.Xamarin.UI/Converters/ValueConverters/DateConverter.cs, src/Tests/DIPS.Xamarin.UI.Tests/Converters/ValueConverters/DateConverterTests.cs
DateConverter: Removed starting 0 from day on english dates
=> DateConverter: Removed starting 0 from day on english dates

src/DIPS.Xamarin.UI/Controls/Popup/PopupBehavior.cs, src/DIPS.Xamarin.UI/Controls/Popup/PopupLayout.xaml.cs, src/DIPS.Xamarin.UI/Controls/TimePicker/TimePicker.xaml.cs, src/DIPS.Xamarin.UI/Extensions/VisualElementExtensions.cs, src/Samples/DIPS.Xamarin.UI.Samples/Controls/Popup/PopupPage.xaml, src/Samples/DIPS.Xamarin.UI.Samples/Controls/Popup/PopupPage.xaml.cs, src/Samples/DIPS.Xamarin.UI.Samples/Controls/Popup/PopupPageViewModel.cs, src/Samples/DIPS.Xamarin.UI.Samples/Controls/Popup/ViewModel.cs
- Added IsOpen to `PopupBehavior`.
- [-] I have added unit tests
=> IsOpen binding for Popup

src/DIPS.Xamarin.UI/Controls/RadioButtonGroup/RadioButtonGroup.xaml, src/Samples/DIPS.Xamarin.UI.Samples/Controls/RadioButtonGroup/RadioButtonGroupPage.xaml
=> Removed crashing scrollviewer

src/DIPS.Xamarin.UI/Controls/Sheet/SheetBehavior.cs
- Shadow should not be default on on iOS
=> Set default shadow to false

src/DIPS.Xamarin.UI/Controls/Modality/ModalityLayout.xaml.cs, src/DIPS.Xamarin.UI/Controls/Sheet/SheetBehavior.cs, src/Samples/DIPS.Xamarin.UI.Samples/Controls/Sheet/SheetPage.xaml
Refactored internal sheetbehavior
- Sheet
- Improved `OnOpen` and `OnClose` events / command
- Internal refactoring
=> Improved when events and commands are invoked / executed

src/DIPS.Xamarin.UI/Controls/Content/ContentControl.cs, src/Samples/DIPS.Xamarin.UI.Samples/Controls/Content/ContentControlPage.xaml, src/Samples/DIPS.Xamarin.UI.Samples/Controls/Content/ContentControlTemplateSelector.cs, src/Samples/DIPS.Xamarin.UI.Samples/Controls/Content/ContentControlViewModel.cs, src/Samples/DIPS.Xamarin.UI.Samples/Controls/Content/ViewModel1.cs, src/Tests/DIPS.Xamarin.UI.Tests/Controls/Content/ContentControlTests.cs
- Added selectorItem for ContentControl
```xml
<content:ContentControl
Grid.Row="1"
BindingContext="{Binding VM1}"
SelectorItem="{Binding SwapTemplate}"
TemplateSelector="{StaticResource boolSelector}" />
```
=> Added selectorItem for ContentControl

src/DIPS.Xamarin.UI/AssemblyInfo.cs, src/DIPS.Xamarin.UI/Controls/Content/DataTemplateSelectors/BooleanDataTemplateSelector.cs, src/DIPS.Xamarin.UI/DIPS.Xamarin.UI.csproj, src/Samples/DIPS.Xamarin.UI.Samples/Controls/Content/ContentControlPage.xaml, src/Samples/DIPS.Xamarin.UI.Samples/Controls/Content/ContentControlTemplateSelector.cs, src/Tests/DIPS.Xamarin.UI.Tests/Controls/Content/DataTemplateSelectors/BooleanDataTemplateSelectorTests.cs, src/Tests/DIPS.Xamarin.UI.Tests/DIPS.Xamarin.UI.Tests.csproj
- Added boolean data template selector
=> Added boolean data template selector

src/DIPS.Xamarin.UI/Converters/ValueConverters/AdditionConverter.cs, src/Samples/DIPS.Xamarin.UI.Samples/Converters/ConvertersPage.xaml, src/Samples/DIPS.Xamarin.UI.Samples/Converters/ConvertersViewModel.cs, src/Samples/DIPS.Xamarin.UI.Samples/Converters/ValueConverters/AdditionConverterPage.xaml, src/Samples/DIPS.Xamarin.UI.Samples/Converters/ValueConverters/AdditionConverterPage.xaml.cs, src/Samples/DIPS.Xamarin.UI.Samples/Converters/ValueConverters/MultiplicationConverterPage.xaml, src/Samples/DIPS.Xamarin.UI.Samples/Converters/ValueConverters/MultiplicationConverterPage.xaml.cs, src/Samples/DIPS.Xamarin.UI.Samples/DIPS.Xamarin.UI.Samples.csproj, src/Tests/DIPS.Xamarin.UI.Tests/Converters/ValueConverters/AdditionConverterTests.cs, src/Tests/DIPS.Xamarin.UI.Tests/TestHelpers/ValueConverterExtensions.cs
- Added AdditionConverter
- Added sample page for MultiplicationConverter
=> Added AdditionConverter

src/DIPS.Xamarin.UI/Controls/FloatingActionMenu/MenuButton.xaml, src/DIPS.Xamarin.UI/Controls/FloatingActionMenu/MenuButton.xaml.cs
- Fixed clipping of text in title
=> Title text has its own font family

src/DIPS.Xamarin.UI/Controls/FloatingActionMenu/FloatingActionMenuBehaviour.cs, src/DIPS.Xamarin.UI/Internal/Xaml/FloatingActionMenu.xaml, src/Samples/DIPS.Xamarin.UI.Samples/Controls/FloatingActionMenu/FloatingActionMenuPage.xaml
- Added `IsVisible `to `FloatingActionMenuBehavior`
- Closes #145
=> Added IsVisible to FloatingActionMenuBehavior

src/DIPS.Xamarin.UI/Controls/Sheet/SheetBehavior.cs, src/DIPS.Xamarin.UI/Internal/Xaml/SheetView.xaml.cs, src/IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro.csproj, src/IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/Github159/Github159.xaml, src/IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/Github159/Github159.xaml.cs, src/IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/MainPage.xaml, src/IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/MainViewModel.cs
VerticalContentAlignment now affects the internal view when changed
- Fixes #159
=> VerticalContentAlignment now affects the internal view when changed

src/DIPS.Xamarin.UI/Internal/Xaml/SheetView.xaml
- Removed the row spacing so the content of the sheet view overlaps the whole content area
=> Removed default row spacing

src/DIPS.Xamarin.UI/Internal/Xaml/SheetView.xaml
- Increased header title and header button sizes
- Header title should be slightly larger than the header buttons. This matches our UX guidelines.
=> Increased header title and header button sizes

src/DIPS.Xamarin.UI/Internal/Xaml/SheetView.xaml
- Fixed sheet header visibility when not desired
=> Fixed sheet header visibility when not desired

src/DIPS.Xamarin.UI/Controls/Sheet/CancelSheetCommand.cs, src/DIPS.Xamarin.UI/Controls/Sheet/SheetBehavior.cs, src/DIPS.Xamarin.UI/Internal/Xaml/SheetView.xaml, src/Tests/DIPS.Xamarin.UI.Tests/Commands/CancelSheetCommandTests.cs
- Added `Task<bool>` option to CancelSheetCommand
=> Added `Task<bool>` option to CancelSheetCommand

src/DIPS.Xamarin.UI/Controls/Sheet/SheetBehavior.cs, src/DIPS.Xamarin.UI/Internal/Xaml/SheetView.xaml, src/DIPS.Xamarin.UI/Internal/Xaml/SheetView.xaml.cs
- Added clicked and cancel events to sheet behavior
=> Added clicked and cancel events to sheet behavior

src/DIPS.Xamarin.UI/Controls/FloatingActionMenu/MenuButton.xaml, src/DIPS.Xamarin.UI/Controls/FloatingActionMenu/MenuButton.xaml.cs, src/Samples/DIPS.Xamarin.UI.Samples/Controls/FloatingActionMenu/FloatingActionMenuPage.xaml
- #175 Added BadgeFontFamily for FloatingNavigationMenu badge
=> Add BadgeFontFamily for FloatingNavigationMenu badge

src/DIPS.Xamarin.UI/Controls/Slidable/DefaultSliderView.cs, src/DIPS.Xamarin.UI/Controls/Slidable/SlidableLayout.cs, src/DIPS.Xamarin.UI/Util/AccelerationService.cs, src/Samples/DIPS.Xamarin.UI.Samples/Controls/SlideLayout/SlideLayoutPage.xaml
- Acceleration based on time on slidable layout.
- Tapgesture to stop the sliding
=> Fixed acceleration by time and tap to stop

src/DIPS.Xamarin.UI/Internal/Xaml/FloatingActionMenu.xaml.cs, src/IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro.csproj, src/IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/Github185/Github185Page.xaml, src/IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/Github185/Github185Page.xaml.cs, src/IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/MainPage.xaml, src/IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/MainViewModel.cs
- Made sure IsVisible is respected for MenuButton in FloatingActionMenu 
- Closes #185 
=> Made sure IsVisible is respected for MenuButton in FloatingActionMenu

LICENSE
- Changed license to follow DIPS Open Source Policy created by @trondd
=> Changed license to follow DIPS Open Source Policy

dips.xamarin.ui.nuspec, src/DIPS.Xamarin.UI.Android/DIPS.Xamarin.UI.Android.csproj, src/DIPS.Xamarin.UI.iOS/DIPS.Xamarin.UI.iOS.csproj, src/DIPS.Xamarin.UI/AssemblyInfo.cs, src/DIPS.Xamarin.UI/Converters/MultiValueConverters/LogicalExpressionConverter.cs, src/DIPS.Xamarin.UI/DIPS.Xamarin.UI.csproj, src/DIPS.Xamarin.UI/Internal/Utilities/XamlParseExceptionExtensions.cs, src/DIPS.Xamarin.UI/Internal/Xaml/SheetView.xaml, src/IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro.Android/DIPS.Xamarin.Forms.IssuesRepro.Android.csproj, src/IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro.Android/Resources/Resource.designer.cs, src/IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro.iOS/DIPS.Xamarin.Forms.IssuesRepro.iOS.csproj, src/IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro.csproj, src/Samples/DIPS.Xamarin.UI.InternalShared/DIPS.Xamarin.UI.InternalShared.csproj, src/Samples/DIPS.Xamarin.UI.Samples.Android/DIPS.Xamarin.UI.Samples.Android.csproj, src/Samples/DIPS.Xamarin.UI.Samples.iOS/DIPS.Xamarin.UI.Samples.iOS.csproj, src/Samples/DIPS.Xamarin.UI.Samples/Controls/Sheet/SheetPage.xaml, src/Samples/DIPS.Xamarin.UI.Samples/Converters/ConvertersPage.xaml, src/Samples/DIPS.Xamarin.UI.Samples/Converters/ConvertersViewModel.cs, src/Samples/DIPS.Xamarin.UI.Samples/Converters/MultiValueConverters/LogicalExpressionConverterPage.xaml, src/Samples/DIPS.Xamarin.UI.Samples/Converters/MultiValueConverters/LogicalExpressionConverterPage.xaml.cs, src/Samples/DIPS.Xamarin.UI.Samples/DIPS.Xamarin.UI.Samples.csproj, src/Tests/DIPS.Xamarin.UI.Tests/Converters/MultiValueConverters/LogicalExpressionConverterTests.cs, src/Tests/DIPS.Xamarin.UI.Tests/DIPS.Xamarin.UI.Tests.csproj, src/Tests/DIPS.Xamarin.UI.Tests/TestHelpers/MultiValueConverterExtensions.cs
- Added `LogicalExpressionConverter`
- Bumped Xamarin.Forms to `4.7.0`
- Made sure sheet title bar is visible for the different cases where it should be visible
=> Added LogicalExpressionConverter

src/DIPS.Xamarin.UI/Controls/FloatingActionMenu/MenuButton.xaml.cs
- Fixed an issue where the menu buttons are not visible
=> Default visiblity property for MenuButton is now true

src/Samples/DIPS.Xamarin.UI.Samples/Converters/ConvertersPage.xaml, src/Samples/DIPS.Xamarin.UI.Samples/Converters/ConvertersViewModel.cs
- Corrected PositionInListConverter samples
=> Corrected PositionInListConverter samples

src/DIPS.Xamarin.UI/Controls/DatePicker/DatePicker.xaml.cs, src/IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro.csproj, src/IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/Github203/Github203.xaml, src/IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/Github203/Github203.xaml.cs, src/IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/MainPage.xaml, src/IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/MainViewModel.cs
=> Added DateSelected event to the picker.

src/DIPS.Xamarin.UI/Controls/FloatingActionMenu/FloatingActionMenuBehaviour.cs, src/DIPS.Xamarin.UI/Controls/FloatingActionMenu/MenuButton.xaml, src/DIPS.Xamarin.UI/Controls/FloatingActionMenu/MenuButton.xaml.cs, src/DIPS.Xamarin.UI/Controls/Modality/ModalityLayout.xaml.cs, src/DIPS.Xamarin.UI/Internal/Xaml/FloatingActionMenu.xaml, src/DIPS.Xamarin.UI/Internal/Xaml/FloatingActionMenu.xaml.cs, src/Samples/DIPS.Xamarin.UI.Samples/Controls/FloatingActionMenu/FloatingActionMenuPage.xaml
Added a `Source` property to menubutton.
Closes #201 
=> Added support for an image to menubutton

src/Tests/DIPS.Xamarin.UI.Tests/Converters/ValueConverters/TimeConverterTests.cs
- Made sure that all tests that uses the static Clock is ran in sequence
=> Made sure that all tests that uses the static Clock is ran in sequence

src/Samples/DIPS.Xamarin.UI.Samples/Controls/Sheet/SheetPage.xaml
- Readded properties to sheet sample page
=> Readded properties to sheet sample page

dips.xamarin.ui.nuspec
- Added target to LICENSE file to nuspec
=> Added target to LICENSE file

src/DIPS.Xamarin.UI.iOS/DIPS.Xamarin.UI.iOS.csproj
Invalid config has been added to the csproj file. Removing it.
=> Remove invalid csproj config

src/DIPS.Xamarin.UI/Controls/Sheet/SheetBehavior.cs, src/DIPS.Xamarin.UI/Internal/Xaml/SheetView.xaml
=> Added label sizes for title, action / cancel buttons

dips.xamarin.ui.nuspec
- Made sure the resource file is included in for iOS
=> Made sure the resource file is included in for iOS

src/DIPS.Xamarin.UI/Controls/RadioButtonGroup/RadioButtonGroup.xaml, src/DIPS.Xamarin.UI/Controls/RadioButtonGroup/RadioButtonGroup.xaml.cs, src/DIPS.Xamarin.UI/Internal/Xaml/RadioButton.xaml, src/DIPS.Xamarin.UI/Internal/Xaml/RadioButton.xaml.cs, src/Samples/DIPS.Xamarin.UI.Samples/Controls/RadioButtonGroup/RadioButtonGroupPage.xaml
=> Added text color property to radiobutton

src/DIPS.Xamarin.UI/Controls/RadioButtonGroup/RadioButtonGroup.xaml.cs, src/IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro.csproj, src/IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/Github244/Github244.xaml, src/IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/Github244/Github244.xaml.cs
- Added radio button padding property to radio button group 
=> Added radio button group padding

src/DIPS.Xamarin.UI/Controls/TrendGraph/TrendGraph.xaml.cs, src/IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro.Android/DIPS.Xamarin.Forms.IssuesRepro.Android.csproj, src/IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro.iOS/DIPS.Xamarin.Forms.IssuesRepro.iOS.csproj, src/IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro.csproj, src/IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/Github246/Github246.xaml, src/IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/Github246/Github246.xaml.cs, src/Samples/DIPS.Xamarin.UI.Samples.Android/DIPS.Xamarin.UI.Samples.Android.csproj, src/Samples/DIPS.Xamarin.UI.Samples.iOS/DIPS.Xamarin.UI.Samples.iOS.csproj, src/Samples/DIPS.Xamarin.UI.Samples/DIPS.Xamarin.UI.Samples.csproj
- Application crash when using Box view in trend graph
- Upgrade XF version to 4.8.0.1560 for Samples and ReproIssues
=> Fix 246 -  app crash when using box views in trend graph

src/DIPS.Xamarin.UI.Android/DIPS.Xamarin.UI.Android.csproj, src/DIPS.Xamarin.UI.Android/InternalButtonRenderer.cs, src/DIPS.Xamarin.UI.Android/Library.cs, src/DIPS.Xamarin.UI/Internal/InternalButton.cs, src/DIPS.Xamarin.UI/Internal/Xaml/SheetView.xaml, src/IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro.csproj, src/IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/Github248/Github248.xaml, src/IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/Github248/Github248.xaml.cs
- Fixed alignment in cancel and action buttons in sheet view. 
1. Android - OPPO F11 Pro
2. iOS Simulator - iPhone11
=> Set alignment for buttons in SheetView

src/DIPS.Xamarin.UI/Controls/RadioButtonGroup/RadioButtonGroup.xaml.cs, src/DIPS.Xamarin.UI/Internal/Xaml/RadioButton.xaml, src/DIPS.Xamarin.UI/Internal/Xaml/RadioButton.xaml.cs, src/Samples/DIPS.Xamarin.UI.Samples/Controls/RadioButtonGroup/RadioButtonGroupPage.xaml
- Added bindable property to allow setting font size
=> [Enhancement-262] Allow setting font size in Radio group

src/DIPS.Xamarin.UI/Controls/Slidable/PanEventArgs.cs, src/DIPS.Xamarin.UI/Controls/Slidable/SlidableLayout.cs, src/Samples/DIPS.Xamarin.UI.Samples/Controls/SlideLayout/SlideLayoutPage.xaml, src/Samples/DIPS.Xamarin.UI.Samples/Controls/SlideLayout/SlideLayoutPage.xaml.cs, src/Samples/DIPS.Xamarin.UI.Samples/Controls/SlideLayout/SlideLayoutViewModel.cs
- Remove drag/acceleration effect if needed when gesture is ended.
- Added pan start and end events.
=> Toggle drag animation on pan end.

src/DIPS.Xamarin.UI.Android/Library.cs, src/DIPS.Xamarin.UI.iOS/Library.cs
=> Check if Library is already initialized

src/DIPS.Xamarin.UI/Controls/FloatingActionMenu/FloatingActionMenuBehaviour.cs
=> Added badge visibility

src/DIPS.Xamarin.UI.Android/Library.cs, src/DIPS.Xamarin.UI.Android/VibrationService.cs, src/DIPS.Xamarin.UI/Vibration/Vibration.cs, src/Samples/DIPS.Xamarin.UI.Samples.Android/MainActivity.cs
=> Android Init requires Activity.

src/DIPS.Xamarin.UI/Converters/ValueConverters/ValueConverterGroup.cs
=> Update namespace of ValueConverterGroup

src/DIPS.Xamarin.UI.Android/VibrationService.cs
=> Wrapped VibrationEffects in version checks

src/DIPS.Xamarin.UI/Controls/FloatingActionMenu/FloatingActionMenuBehaviour.cs
=> Fixed the empty badge appearing

src/DIPS.Xamarin.UI.Android/VibrationService.cs
=> Added permission check to vibration functions

src/DIPS.Xamarin.UI/Converters/ValueConverters/ObjectToBoolConverter.cs, src/Samples/DIPS.Xamarin.UI.Samples/Converters/ConvertersPage.xaml, src/Samples/DIPS.Xamarin.UI.Samples/Converters/ConvertersViewModel.cs, src/Samples/DIPS.Xamarin.UI.Samples/Converters/ValueConverters/BoolToObjectConverterPage.xaml.cs, src/Samples/DIPS.Xamarin.UI.Samples/Converters/ValueConverters/ObjectToBoolConverterPage.xaml, src/Samples/DIPS.Xamarin.UI.Samples/Converters/ValueConverters/ObjectToBoolConverterPage.xaml.cs, src/Tests/DIPS.Xamarin.UI.Tests/Converters/ValueConverters/ObjectToBoolConverterTests.cs
- Added 'ObjectToBoolConverter' which uses an object's `.Equals(object? obj)` to convert it to a boolean value.
=> Added 'ObjectToBoolConverter' class

src/DIPS.Xamarin.UI/Controls/Sheet/SheetBehaviorProps.cs
- Changed default value of `SheetOpeningStrategy` to `FirstSnapPoint`.
=> Changed default value of `SheetOpeningStrategy`

src/DIPS.Xamarin.UI.Android/DIPS.Xamarin.UI.Android.csproj, src/DIPS.Xamarin.UI.iOS/DIPS.Xamarin.UI.iOS.csproj, src/DIPS.Xamarin.UI.iOS/Info.plist, src/DIPS.Xamarin.UI/Controls/Sheet/SheetBehavior.cs
- Fixed a bug where sheet disappeared or layout broken when orientation changed
=> Fix for sheet broken when orientation changes

src/DIPS.Xamarin.UI.Android/Util/SlidableLayoutContentView.cs, src/Samples/DIPS.Xamarin.UI.Samples/Controls/DatePicker/DatePickerPage.xaml
- Fixed bug where items in SlidableContentLayout sometimes could not be tapped
=> [Android] Fixed a bug in SlidableContentLayout 

src/DIPS.Xamarin.UI/Resources/Colors/ColorPalette.cs
=> Added aqua color

src/DIPS.Xamarin.UI/Converters/ValueConverters/DateAndTimeConverter.cs, src/DIPS.Xamarin.UI/Converters/ValueConverters/DateConverter.cs, src/DIPS.Xamarin.UI/Converters/ValueConverters/DateTimeFormatter.cs, src/DIPS.Xamarin.UI/Converters/ValueConverters/TimeConverter.cs, src/DIPS.Xamarin.UI/DateTimeFormatter.cs, src/Samples/DIPS.Xamarin.UI.Samples/App.xaml.cs
=> Added DateTimeFormatter

catalog-info.yaml
=> added backstage catalog info
