.github/PULL_REQUEST_TEMPLATE/pull_request_template.md
src/DIPS.Xamarin.UI/Converters/ValueConverters/BoolToObjectConverter.cs
src/Samples/DIPS.Xamarin.UI.Samples/Converters/ConvertersPage.xaml
src/Samples/DIPS.Xamarin.UI.Samples/Converters/ConvertersPage.xaml.cs
src/Samples/DIPS.Xamarin.UI.Samples/Converters/ConvertersViewModel.cs
src/Samples/DIPS.Xamarin.UI.Samples/Converters/ValueConverters/BoolToObjectConverterPage.xaml
src/Samples/DIPS.Xamarin.UI.Samples/Converters/ValueConverters/BoolToObjectConverterPage.xaml.cs
src/Samples/DIPS.Xamarin.UI.Samples/Converters/ValueConverters/InvertedBoolConverterPage.xaml
src/Samples/DIPS.Xamarin.UI.Samples/Converters/ValueConverters/IsEmptyConverterPage.xaml
src/Samples/DIPS.Xamarin.UI.Samples/DIPS.Xamarin.UI.Samples.csproj
src/Samples/DIPS.Xamarin.UI.Samples/MainPage.xaml
src/Samples/DIPS.Xamarin.UI.Samples/MainViewModel.cs
src/Tests/DIPS.Xamarin.UI.Tests/Converters/ValueConverters/BoolToObjectConverterTests.cs

- Added `BoolToObjectConverter`
- This converter can be used by our consumers to convert a boolean value to whatever object they want. 
You want to change the `Opacity` of a `Label` based on a `boolean` value in your view model.
>*Please add pictures / Gifs if possible

Added BoolToObjectConverter

---

src/DIPS.Xamarin.UI.sln
src/DIPS.Xamarin.UI/Controls/DatePicker/DatePicker.cs
src/DIPS.Xamarin.UI/Extensions/PropertyChangedExtensions.cs
src/IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro.iOS/DIPS.Xamarin.Forms.IssuesRepro.iOS.csproj
src/Samples/DIPS.Xamarin.UI.Samples/Extensions/PropertyChangedViewModel.cs

- Added `RaiseWhenSet` 
- Marke `RaiseAfter` as obsolete because it was confusing and not really fluent.

Renamed `RaiseAfter` to `RaiseWhenSet`

---

src/DIPS.Xamarin.UI/Controls/DatePicker/DatePicker.xaml
src/DIPS.Xamarin.UI/Controls/DatePicker/DatePicker.xaml.cs
src/DIPS.Xamarin.UI/Controls/TimePicker/TimePicker.xaml
src/DIPS.Xamarin.UI/Controls/TimePicker/TimePicker.xaml.cs
src/DIPS.Xamarin.UI/InternalUtils/LabelFontSizeTypeConverter.cs
src/IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro.iOS/DIPS.Xamarin.Forms.IssuesRepro.iOS.csproj
src/IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro.csproj
src/IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/Github86/Github86.xaml
src/IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/Github86/Github86.xaml.cs
src/IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/MainPage.xaml
src/IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/MainViewModel.cs

- Added reproduced bug page
- Added `LabelFontSizeTypeConverter` on `LabelSize` to make sure we handle name font sizes.
- Added `Open()` an `IsOpen` in order for our consumers to be able to open the pickers and to check it it is open.
- None needed
- Fixes #86 

Made sure `LabelSize` support named font sizes.

---

src/DIPS.Xamarin.UI/Converters/ValueConverters/BoolToObjectConverter.cs
src/DIPS.Xamarin.UI/Converters/ValueConverters/MultiplicationConverter.cs
src/Tests/DIPS.Xamarin.UI.Tests/Converters/ValueConverters/MultiplicationConverterTests.cs

- Changed `MultiplicationConverter.Factor` to double
- This is to prevent potential culture variances of the value. If the converter properties has no strong type, XAML will send the property as a string.

Changed `MultiplicationConverter.Factor` to double

---

src/DIPS.Xamarin.UI/Controls/RadioButtonGroup/RadioButtonGroup.xaml
src/DIPS.Xamarin.UI/Internal/Xaml/RadioButton.xaml
src/IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro.csproj
src/IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/Github112/Github112.xaml
src/IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/Github112/Github112.xaml.cs
src/IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/MainPage.xaml
src/IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/MainViewModel.cs

- Removed inner grid and made sure the radiobuttongroups is using its parents alignment options
- Closes #112 

Fixed sizing of radiobuttongroup

---

src/DIPS.Xamarin.UI/Controls/Modality/ModalityLayout.xaml

- Added `IsClippedToBounds=True` to `ModalityLayout`
- The (and other components) inside of the modalitylayout should not be visible outside of the `ModalityLayout`.

Added IsClippedToBounds to ModalityLayout

---

.gitignore
src/DIPS.Xamarin.UI/Controls/TrendGraph/TrendGraph.xaml.cs
src/Samples/DIPS.Xamarin.UI.Samples/Controls/TrendGraph/TrendGraphPage.xaml
src/Samples/DIPS.Xamarin.UI.Samples/Controls/TrendGraph/TrendGraphPage.xaml.cs

Users can now indicate if a value should get a different color if the value is above or below some reference area.
```xml
<dxui:TrendGraph
ItemsSource="{Binding TrendItems}"
LowerBound="{Binding LowerBound}"
UpperBound="{Binding UpperBound}" />
```

Added reference area to trendgraphs

---

src/DIPS.Xamarin.UI/Controls/Slidable/SlidableContentLayout.cs
src/DIPS.Xamarin.UI/Controls/Slidable/SlidableLayout.cs

- Added default value to `Config` property in `SlidableLayout`, and null checks where `Config` is used. 

Bug -  added null checks to Config in SlidableLayout

---

src/DIPS.Xamarin.UI.sln
src/DIPS.Xamarin.UI/Controls/FloatingActionMenu/FloatingActionMenuBehaviour.cs
src/DIPS.Xamarin.UI/Controls/Modality/IModalityHandler.cs
src/DIPS.Xamarin.UI/Controls/Modality/ModalityLayout.xaml.cs
src/DIPS.Xamarin.UI/Controls/Popup/PopupBehavior.cs
src/DIPS.Xamarin.UI/Controls/Sheet/SheetBehavior.cs
src/DIPS.Xamarin.UI/Internal/Xaml/FloatingActionMenu.xaml.cs
src/Samples/DIPS.Xamarin.UI.Samples/Controls/FloatingActionMenu/FloatingActionMenuPage.xaml
src/Samples/DIPS.Xamarin.UI.Samples/Controls/Popup/PopupPage.xaml
src/Samples/DIPS.Xamarin.UI.Samples/Controls/Sheet/SheetPage.xaml

- Added properties to `Sheet`, `Popup` and `FloatingActionMenu` to turn off closing the modalities when the user taps the overlay.
- Added property to `ModalityLayout` to turn off tapping the overlay to close for all it's child modalities.

Added the possibility of turn off tapping the overlay for modalities

---

src/DIPS.Xamarin.UI/Controls/Sheet/SheetBehavior.cs
src/IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro.Android/Resources/Resource.designer.cs
src/IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro.csproj
src/IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/Github150/Github150.xaml
src/IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/Github150/Github150.xaml.cs
src/IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/MainPage.xaml
src/IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/MainViewModel.cs
src/Samples/DIPS.Xamarin.UI.Samples/Controls/Sheet/SheetPage.xaml
src/Samples/DIPS.Xamarin.UI.Samples/Controls/Sheet/SheetPage.xaml.cs

Sheet 
- Added a original position member field to keep the original position
- Added a new property to make sure the sheet remembers position

Sheet reset position to orignal position when re-opened, fixed #150

---

src/DIPS.Xamarin.UI.Android/DIPS.Xamarin.UI.Android.csproj
src/DIPS.Xamarin.UI.Android/Library.cs
src/DIPS.Xamarin.UI.Android/Util/Inspector.cs
src/DIPS.Xamarin.UI.iOS/DIPS.Xamarin.UI.iOS.csproj
src/DIPS.Xamarin.UI.iOS/Library.cs
src/DIPS.Xamarin.UI.iOS/Util/Inspector.cs
src/DIPS.Xamarin.UI/AssemblyInfo.cs
src/DIPS.Xamarin.UI/Extensions/ViewExtensions.cs
src/DIPS.Xamarin.UI/Internal/Utilities/Inspector.cs

- Documentation is written [here](https://github.com/DIPSAS/DIPS.Xamarin.UI/wiki/Inspector) and pasted below.
The below documentation is from our [wiki](https://github.com/DIPSAS/DIPS.Xamarin.UI/wiki/Inspector)
----
When working with `Xamarin.Forms` we have the pleasure of having shared UI code to create our human interfaces for both Android and iOS. You will spend most of your time in this shared code.
There are cases where you will have to dive down to the platforms in order to customize the appearance or maybe subscribe to / delegate events for different controls. `Xamarin.Forms` gives us the possibilities of using [Custom Renderers](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/) or [Effects](https://docs.microsoft.com/en-us/xamarin/xamarin-for …

Added Inspector, a API to inspect the native control of a shared control.

---

src/DIPS.Xamarin.UI/Controls/Modality/ModalityLayout.xaml.cs
src/Samples/DIPS.Xamarin.UI.Samples/Controls/Popup/PopupPage.xaml

When bumping Xamarin.Forms to the latest version in my private project I noticed that the overlay of ModalityLayout did not fade down anymore on iOS. I think this is related to https://github.com/xamarin/Xamarin.Forms/issues/10024. 
- Removed Frame Shadow on ModalityLayout overlay.
- Removed shadow from popup page samples

Removed shadow on modalitylatout overlay

---

src/DIPS.Xamarin.UI/Controls/Slidable/DefaultSliderView.cs
src/DIPS.Xamarin.UI/Controls/Slidable/SlidableLayout.cs
src/DIPS.Xamarin.UI/Controls/Slidable/SlidableProperties.cs
src/Samples/DIPS.Xamarin.UI.Samples/Controls/SlideLayout/SlideLayoutPage.xaml
src/Samples/DIPS.Xamarin.UI.Samples/Controls/SlideLayout/SlideLayoutPage.xaml.cs
src/Samples/DIPS.Xamarin.UI.Samples/Controls/SlideLayout/SlideLayoutViewModel.cs

- SlidableLayout has a different initial hold id set. To not override values set from the ViewModel

SlidableLayout can now update from ViewModel before being used.

---

src/DIPS.Xamarin.UI/Internal/Xaml/FloatingActionMenu.xaml.cs

#172
Floating button keeps correct position when you rotate the device

Floating button keeps X position on rotation

---

src/DIPS.Xamarin.UI/Controls/FloatingActionMenu/MenuButton.xaml.cs
src/DIPS.Xamarin.UI/Internal/Xaml/FloatingActionMenu.xaml.cs
src/DIPS.Xamarin.UI/Library.cs
src/Samples/DIPS.Xamarin.UI.Samples/Controls/FloatingActionMenu/FloatingActionMenuPage.xaml
src/Samples/DIPS.Xamarin.UI.Samples/Controls/FloatingActionMenu/FloatingActionMenuPage.xaml.cs

Removes menubutton properly when toggling visibility when menu is expanded.
- Fixed #187 

Menubutton visibility toggle

---

src/DIPS.Xamarin.UI/Controls/Sheet/SheetBehavior.cs
src/DIPS.Xamarin.UI/Internal/Xaml/SheetView.xaml.cs
src/Samples/DIPS.Xamarin.UI.Samples/Controls/Sheet/SheetPage.xaml
src/Samples/DIPS.Xamarin.UI.Samples/Controls/Sheet/SheetPage.xaml.cs

…in position when the sheets is not dragging anymore
- The `MinPosition` is now used to determine when the sheet should close if `ShouldAutoClose` is set to true.
- `ShouldAutoClose` default is set to `true`
- The sheet does not auto close / snap into `MinPosition` until the user has finished dragging it.
- Fixes #215

Added ShouldAutoClose to sheet and changed the behavior when dragging with autoclose

---

src/DIPS.Xamarin.UI/Controls/DatePicker/DatePicker.xaml.cs
src/Samples/DIPS.Xamarin.UI.Samples/Controls/DatePicker/DatePickerPage.xaml

- The datepicker now unfocus when you use the extra button.
- Added both `Focus / Unfocus` and `Open / Close` methods for the consumer.

The datepicker now unfocus when you use the extra button

---

src/DIPS.Xamarin.UI/Controls/DatePicker/DatePicker.xaml.cs

…icker after selected when using WhenDone strategy
- The iOS datepicker is now synced when the user has closed the iOS datepicker but chosen to set date when done

The iOS datepicker is now synced when the user has closed the iOS datepicker but chosen to set date when done

---

src/DIPS.Xamarin.UI/Controls/Sheet/SheetBehavior.cs
src/DIPS.Xamarin.UI/Internal/Xaml/SheetView.xaml
src/Samples/DIPS.Xamarin.UI.Samples/Controls/Sheet/SheetPage.xaml

- Enables the user to change title font attributes
- Default is still **bold** as it was before.
- TitleTextColor default value is now the same as Label.TextColorProperty.DefaultValue. This resolve an issue on iOS where the label did not get bold when using a different color. This might be a Xam.Forms issue.

Enables the user to change title font attributes and fix ios title boldness 

---

src/DIPS.Xamarin.UI.sln
src/DIPS.Xamarin.UI/Controls/Toast/Toast.cs
src/DIPS.Xamarin.UI/Controls/Toast/ToastCore.cs
src/DIPS.Xamarin.UI/Converters/ValueConverters/StringCaseConverter.cs
src/Samples/DIPS.Xamarin.UI.Samples/Converters/ValueConverters/StringCaseConverterPage.xaml
src/Samples/DIPS.Xamarin.UI.Samples/Converters/ValueConverters/StringCaseConverterPage.xaml.cs
src/Tests/DIPS.Xamarin.UI.Tests/Converters/ValueConverters/StringCaseConverterTests.cs

- Return `null` as that is a valid case for bindings. Then you can use `TargetNullValue` as well

Removed exception throwing in string case converter

---

src/DIPS.Xamarin.UI/Internal/Xaml/FloatingActionMenu.xaml.cs
src/Samples/DIPS.Xamarin.UI.Samples.Android/DIPS.Xamarin.UI.Samples.Android.csproj
src/Samples/DIPS.Xamarin.UI.Samples/Controls/FloatingActionMenu/FloatingActionMenuPage.xaml

- The `IsOpen` property on floating menu is now toggled before the animation starts. 
Closes #252 

`IsOpen` is set before animations

---

src/DIPS.Xamarin.UI/Converters/ValueConverters/DateAndTimeConverter.cs
src/DIPS.Xamarin.UI/Converters/ValueConverters/DateConverter.cs
src/DIPS.Xamarin.UI/Converters/ValueConverters/TimeConverter.cs
src/DIPS.Xamarin.UI/Extensions/CultureInfoExtensions.cs
src/Samples/DIPS.Xamarin.UI.Samples/Converters/ValueConverters/DateAndTimeConverterPage.xaml.cs
src/Samples/DIPS.Xamarin.UI.Samples/Converters/ValueConverters/DateConverterPage.xaml.cs
src/Samples/DIPS.Xamarin.UI.Samples/Converters/ValueConverters/TimeConverterPage.xaml.cs
src/Tests/DIPS.Xamarin.UI.Tests/Converters/ValueConverters/DateAndTimeConverterTests.cs
src/Tests/DIPS.Xamarin.UI.Tests/Converters/ValueConverters/DateConverterTests.cs
src/Tests/DIPS.Xamarin.UI.Tests/Converters/ValueConverters/TimeConverterTests.cs

- Fixed date/time format in EN-GB
eg: 3rd Dec 2020 13:00
- Fixed date/time format in EN-US
eg: Dec 3rd, 2020 1:00 PM

Supported  date/time format in en-GB

---

src/DIPS.Xamarin.UI/Controls/Toast/ToastCore.cs
src/DIPS.Xamarin.UI/Internal/Xaml/ToastContainer.xaml
src/DIPS.Xamarin.UI/Internal/Xaml/ToastContainer.xaml.cs
src/Samples/DIPS.Xamarin.UI.Samples/Controls/Toast/ToastPage.xaml

- Fixed a bug
When using ToastContainer wrapper, the toast is added and removed to the wrapper which itself is a grid. 
The existing implementation is valid when there is no wrapper used.
This fix following issues
- Reset scroll position of the page when toast appears
- Disable buttons on the view when a toast is being displayed

Add ToastContainer wrapper

---

src/DIPS.Xamarin.UI/Controls/Sheet/SheetBehavior.cs
src/Samples/DIPS.Xamarin.UI.Samples/Controls/Sheet/SheetPage.xaml
src/Samples/DIPS.Xamarin.UI.Samples/Controls/Sheet/SheetPage.xaml.cs

- Ensure that the CanCloseSheet value is respected when the overlay is tapped while the SheetView  is open
- Invoke the CancelCommand when the overlay is tapped while the SheetView is open

Invoke CancelCommand for SheetView when tapping on the overlay

---

src/DIPS.Xamarin.UI/Converters/ValueConverters/DateAndTimeConverter.cs
src/DIPS.Xamarin.UI/Converters/ValueConverters/DateConverter.cs
src/DIPS.Xamarin.UI/Converters/ValueConverters/TimeConverter.cs

- Allow skipping conversion to local time zone with IgnoreLocalTime flag in converter

Convert date time to local time zone before to formatting

---

src/DIPS.Xamarin.UI/Controls/Slidable/SlidableLayout.cs

- Unnecessary null check caused vibration not to work if `SelectedItemChangedCommand` was not set

Removed unnecessary null check

---

src/DIPS.Xamarin.UI/Controls/Slidable/SlidableContentLayout.cs

- Added public Redraw() method for allowing a manual redraw of the content of the `SlidableContentLayout`.

Added public Redraw() method for redrawing slidable content layout

---

src/DIPS.Xamarin.UI/Extensions/Markup/InvertedBoolExtension.cs

- Added a InvertedBool markup extension, this can be used like so:
```xml
<Label IsVisible="{markup:BoolInverter Value={x:Static MyClass.MyStaticBoolProperty}}" />
```

Added InvertedBool markup extension

---

src/DIPS.Xamarin.UI.Android/Util/SlidableLayoutContentView.cs

- Fixed SlidableContentLayout not scrolling on some Samsung devices
- The issue comes from `HistorySize` not always being greater than 0 although there actually are historical points. Therefore, it's better to just manually cache the previous position and scroll based on that

Fixed SlidableContentLayout not scrolling on some Samsung devices

---

src/DIPS.Xamarin.UI.Android/ContextMenu/ContextMenuButtonRenderer.cs
src/DIPS.Xamarin.UI.Android/ContextMenu/ContextMenuHelper.cs
src/DIPS.Xamarin.UI.iOS/ContextMenu/ContextMenuButtonRenderer.cs

- Made sure Android does not crash when a icon is added to the context menu item
- Made sure context menu is closed when app goes to background on both android and iOS

[ContextMenu] Improvements to Android icon and auto-close when app goes to background

---

src/DIPS.Xamarin.UI.Android/ContextMenu/ContextMenuButtonRenderer.cs
src/DIPS.Xamarin.UI.iOS/ContextMenu/ContextMenuButtonRenderer.cs

Made sure to dispose context menu buttons in the platforms correctly to provent crashes if people navigate out of the page that the context menu was added and then send the app to background.

Made sure to dispose context menu buttons in the platforms correctly
